# Default PyTorch Lightning Trainer configuration
_target_: pytorch_lightning.Trainer
accelerator: "auto"  # auto select GPU if available, else CPU
devices: "auto"
max_epochs: 100
# min_epochs: 10 # Optional
# precision: "16-mixed" # if using mixed precision
# log_every_n_steps: 50
# enable_checkpointing: True
# check_val_every_n_epoch: 1
# deterministic: True # if seed_everything is used
